Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"


  # SERVER VM

  config.vm.define "server" do |server|

    server.vm.hostname = "server"

    server.vm.network "private_network",
      ip: "192.168.56.10"


    server.vm.provision "shell",
      path: "provision/server.sh"

  end



  # CLIENT VM

  config.vm.define "client" do |client|

    client.vm.hostname = "client"

    client.vm.network "private_network",
      ip: "192.168.56.20"


    client.vm.provision "shell",
      path: "provision/client.sh"

  end


end
