apiVersion: v1
kind: Pod
metadata:
  name: wordpress-diagnostics
  namespace: dev
spec:
  serviceAccountName: wordpress-diagnostics
  restartPolicy: Never

  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - /bin/sh
        - -c
        - |
          echo "WordPress pods:"
          kubectl get pods -n dev -l app=wordpress
