Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev"

    dev.vm.network "private_network", ip: "192.168.56.13"

    dev.vm.provider "virtualbox" do |vb|
      vb.name = "lesson13-dev"
      vb.memory = 2048
      vb.cpus = 2
    end
  end

end
