Vagrant.configure("2") do |config|

  config.vm.define "dev" do |dev|
    dev.vm.box = "ubuntu/jammy64"
    dev.vm.hostname = "dev"

    dev.vm.network "private_network", ip: "192.168.56.11"

    dev.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "prod" do |prod|
    prod.vm.box = "ubuntu/jammy64"
    prod.vm.hostname = "prod"

    prod.vm.network "private_network", ip: "192.168.56.12"

    prod.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

end
