Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial32" 
  config.vm.box_check_update = false

  config.vm.define "cl" do |client|
    client.vm.hostname = "cl"
    client.vm.network "private_network", ip: "192.168.56.20"
    client.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    client.vm.provision "shell", path: "provision_client.sh", privileged: false
  end

  config.vm.define "sr" do |server|
    server.vm.hostname = "sr"
    server.vm.network "private_network", ip: "192.168.56.10"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
    server.vm.provision "shell", path: "provision_server.sh", privileged: false
  end
end
