apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
data:
  WORDPRESS_DB_HOST: {{ printf "%s:%v" (include "wordpress.mysql.fullname" .) .Values.mysql.service.port | quote }}
  WORDPRESS_DB_NAME: {{ .Values.mysqlAuth.database | quote }}
