apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql
      port: {{ .Values.mysql.service.port }}
      targetPort: mysql
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "wordpress.mysql.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
