apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wordpress.mysql.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "wordpress.wordpress.fullname" . }}
              app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - protocol: TCP
          port: {{ .Values.mysql.service.port }}
