{{- if .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.mysql.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mysql.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size }}
  storageClassName: {{ .Values.mysql.persistence.storageClass }}
  volumeName: {{ include "wordpress.mysql.fullname" . }}-pv
---
{{- end }}

{{- if .Values.wordpress.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wordpress.wordpress.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.wordpress.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}
  volumeName: {{ include "wordpress.wordpress.fullname" . }}-pv
---
{{- end }}
