{{- if .Values.wordpress.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wordpress.wordpress.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wordpress.wordpress.fullname" . }}
  minReplicas: {{ .Values.wordpress.hpa.minReplicas }}
  maxReplicas: {{ .Values.wordpress.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.wordpress.hpa.targetCPUUtilizationPercentage }}
{{- end }}
