Vagrant.configure("2") do |config|

  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.10"
  end

  config.vm.define "store" do |store|
    store.vm.box = "ubuntu/jammy64"
    store.vm.hostname = "store"
    store.vm.network "private_network", ip: "192.168.56.20"
  end

end
